# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: guard_against_physical_delete 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "guard_against_physical_delete"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["MORITA shingo"]
  s.date = "2014-06-13"
  s.description = "Guard against physical delete"
  s.email = "morita@cookpad.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "License.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "guard_against_physical_delete.gemspec",
    "lib/guard_against_physical_delete.rb",
    "lib/guard_against_physical_delete/base.rb",
    "lib/guard_against_physical_delete/physical_delete_error.rb",
    "lib/guard_against_physical_delete/relation.rb",
    "lib/guard_against_physical_delete/support_counter_cache.rb",
    "lib/guard_against_physical_delete/support_counter_cache/3.0.10/associations.rb",
    "lib/guard_against_physical_delete/support_counter_cache/3.2_and_4.0/associations/builder/belongs_to.rb",
    "lib/guard_against_physical_delete/support_counter_cache/associations/builder/belongs_to.rb",
    "spec/database.rb",
    "spec/guard_against_physical_delete/guard_spec.rb",
    "spec/guard_against_physical_delete/support_counter_cache_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/cookpad/guard_against_physical_delete"
  s.rubygems_version = "2.2.2"
  s.summary = "Guard against physical delete"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.10"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["< 2.99"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<countdownlatch>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.10"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<rspec>, ["< 2.99"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<countdownlatch>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.10"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<rspec>, ["< 2.99"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<countdownlatch>, [">= 0"])
  end
end

